CREATE EXTENSION pgcrypto;
\c gamesdb

CREATE TABLE games (    title text,
                        publisher varchar,
                        genre varchar,
                        released int,
                        playtime int
                    );
                        
CREATE TABLE users (        username text NOT NULL PRIMARY KEY,
                            password text NOT NULL,
                            UNIQUE(username)
                            );
                            
                            
                            
INSERT INTO users VALUES('first', crypt('1', gen_salt('bf')));                            
INSERT INTO users (username, password) VALUES('second', crypt('1', gen_salt('bf')));
INSERT INTO users (username, password) VALUES('third', crypt('1', gen_salt('bf')));
INSERT INTO rooms (username, roomname, subs) VALUES('first', 'Public', 'first');




INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Dropzone Commander 2 Player Starter Set', 'Hawk Wargames', 'Miniatures', '2013', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Duel of Ages II', 'Worldspanner', 'Adventure', '2013', 150 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Dungeon Twister 2: Prison', 'Asmodee', 'Adventure', '2009', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('DungeonQuest Revised Edition', 'Arclight', 'Adventure', '2014', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Dungeons & Dragons: Castle Ravenloft Board Game', 'Wizards of the Coast', 'Adventure', '2010', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Dungeons & Dragons: The Legend of Drizzt Board Game', 'Wizards of the Coast', 'Adventure', '2011', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Dust', 'Dust Games', 'Miniatures', '2007', 240 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Earth Reborn', 'Ludically', 'Adventure', '2010', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Eclipse', 'Lautapelit.fi', 'Civilization', '2011', 200 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Eclipse: Rise of the Ancients', 'Asmodee', 'Civilization', '2012', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Elasund: The First City', 'Filosofia �ditions', 'Economic', '2005', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Elder Sign', 'Fantasy Flight Games', 'Adventure', '2011', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Eldritch Horror', 'Fantasy Flight Games', 'Adventure', '2013', 240 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Emergence Event', 'Mercs, LLC', 'Card Game', '2015', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Empire of the Sun', 'GMT Games', 'Nautical', '2005', 360 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Empires of the Void', 'Red Raven Games', 'Science Fiction', '2012', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('End of Empire: 1744-1782', 'Compass Games', 'Age of Reason', '2014', 360 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Enemy Coast Ahead: The Dambuster Raid', 'GMT Games', 'Aviation / Flight', '2014', 0 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('EONS', 'Gamer Nation Studios', 'Space Exploration', '2013', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Escape: The Curse of the Temple', 'Queen Games', 'Adventure', '2012', 10 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Evolution', 'North Star Games, LLC', 'Animals', '2014', 70 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Extra! Extra!', 'Mayfair Games', 'Card Game', '2015', 150 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Fallen', 'Watchtower Games', 'Card Game', '2014', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('A Few Acres of Snow', 'Asmodee', 'Age of Reason', '2011', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Field Commander: Alexander', 'DVG', 'Ancient', '2009', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Field Commander: Napoleon', 'DVG', 'Napoleonic', '2011', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Field Commander: Rommel', 'DVG', 'Wargame', '2008', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Fields of Fire', 'GMT Games', 'Korean War', '2008', 300 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Fighting Formations: Grossdeutschland Motorized Infantry Division', 'GMT Games', 'Wargame', '2011', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Final Frontier', 'Victory Point Games', 'Adventure', '2010', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Firefly: Out to the Black', 'Toy Vault, Inc.', 'Card Game', '2013', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Firefly: Shiny Dice', 'Upper Deck Entertainment', 'Dice', '2015', 30 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Firefly: The Game', 'Battlefront Miniatures Ltd', 'Movies / TV / Radio theme', '2013', 240 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Five Tribes', 'Days of Wonder', 'Arabian', '2014', 80 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Flash Point: Fire Rescue', 'Indie Boards & Cards', 'Adventure', '2011', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Fleet Commander: Nimitz', 'DVG', 'Nautical', '2014', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Flick ''em Up!', 'Ghenos Games', 'Action / Dexterity', '2015', 30 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Flying Colors', 'GMT Games', 'Age of Reason', '2005', 240 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('For the People', 'Avalon Hill', 'American Civil War', '1998', 360 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Forbidden Desert', 'Cocktail Games', 'Adventure', '2013', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Foretold: Rise of a God', 'Apotheosis Games LLC', 'Card Game', '2014', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Forge War', 'Cephalofair Games', 'Adventure', '2015', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Formula D', 'ADC Blackfire Entertainment', 'Racing', '2008', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Fortress America', 'Milton Bradley', 'Science Fiction', '1986', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Fortune and Glory: The Cliffhanger Game', 'Flying Frog Productions', 'Adventure', '2011', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Frag', 'Pegasus Spiele', 'Fighting', '2001', 30 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Freedom: The Underground Railroad', '(Web published)', 'American Civil War', '2012', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Friday', '2F-Spiele', 'Card Game', '2011', 25 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Frontline: D-Day', 'DVG', 'Card Game', '2010', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Galaxy Command', 'Worthington Publishing, LLC', 'Science Fiction', '2015', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Galaxy Defenders', 'Gremlin Project', 'Fighting', '2014', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('The Game of France, 1940: German Blitzkrieg in the West', 'Avalon Hill', 'Wargame', '1972', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('A Game of Thrones: The Board Game (Second Edition)', 'Fantasy Flight Games', 'Bluffing', '2011', 240 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('A Game of Thrones: The Card Game', 'Edge Entertainment', 'Card Game', '2008', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('A Game of Thrones: The Card Game (Second Edition)', 'ADC Blackfire Entertainment', 'Card Game', '2015', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Gary Gouda', 'HABA - Habermaa� GmbH', 'Children''s Game', '2011', 10 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Gears of War: The Board Game', 'Edge Entertainment', 'Fighting', '2011', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Gearworld: The Borderlands', 'Edge Entertainment', 'Industry / Manufacturing', '2013', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Genesis: Empires and Kingdoms of the Ancient Middle East', 'GMT Games', 'Ancient', '2015', 600 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Ghost Stories', 'Repos Production', 'Fantasy', '2008', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Ghostbusters: The Board Game', 'Cryptozoic Entertainment', 'Movies / TV / Radio theme', '2015', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Global Mogul', 'Mayfair Games', 'Economic', '2013', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Gloom', 'Atlas Games', 'Card Game', '2005', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('The Golden Ages', 'Quined Games', 'Civilization', '2014', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Golem Arcana', 'Harebrained Schemes', 'Electronic', '2014', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Grand Conquest', 'Numbskull Games', 'Abstract Strategy', '2006', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Grant''s Gamble', 'Worthington Publishing, LLC', 'American Civil War', '2015', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Gravwell: Escape from the 9th Dimension', 'Cryptozoic Entertainment', 'Card Game', '2013', 20 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Greenland', 'Sierra Madre Games', 'Card Game', '2014', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Ground Floor', 'Tasty Minstrel Games', 'City Building', '2012', 150 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Guillotine', 'AMIGO Spiel + Freizeit GmbH', 'Card Game', '1998', 30 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('The Guns of Gettysburg', 'Mercury Games', 'American Civil War', '2013', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Gunship: First Strike!', 'Escape Pod Games', 'Card Game', '2013', 30 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Le Havre', 'Lookout Games', 'City Building', '2008', 200 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Healthy Heart Hospital', 'Victory Point Games', 'Economic', '2015', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Heavy Steam', 'Greenbrier Games', 'Science Fiction', '2015', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Hegemonic', 'Minion Games', 'Civilization', '2013', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Heroes of Normandie', 'Devil Pig Games', 'Wargame', '2014', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('High and Tight', 'Victory Point Games', 'Sports', '2011', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('High Frontier', 'Sierra Madre Games', 'Civilization', '2010', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Historia', 'Arclight', 'Civilization', '2014', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Hold the Line', 'Worthington Games', 'Age of Reason', '2008', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Homeland: The Game', 'Battlefront Miniatures Ltd', 'Deduction', '2015', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Hornet Leader: Carrier Air Operations', 'DVG', 'Aviation / Flight', '2010', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Horus Heresy', 'Edge Entertainment', 'Miniatures', '2010', 135 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('A House Divided', 'Dise�os Orbitales', 'American Civil War', '1981', 240 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('The Hunters: German U-Boats at War, 1939-43', 'Consim Press', 'Wargame', '2013', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Hyperborea', 'Asterion Press', 'Civilization', '2014', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Ideology: The War of Ideas', 'Z-Man Games', 'Political', '2003', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Illuminati:  Deluxe Edition', 'Descartes Editeur', 'Card Game', '1987', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Imperial Settlers', 'Portal Games', 'Ancient', '2014', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Impulse', 'Asmadi Games', 'Bluffing', '2013', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('In Magnificent Style', 'Victory Point Games', 'American Civil War', '2012', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Infection: Humanity''s Last Gasp', 'Victory Point Games', 'Medical', '2013', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Infinite City', 'Alderac Entertainment Group', 'City Building', '2009', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Innovation', 'Asmadi Games', 'Card Game', '2010', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Invaders', 'White Goblin Games', 'Card Game', '2013', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Iron and Oak', 'GMT Games', 'American Civil War', '2013', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Island Fortress', 'Frost Forge Games', 'Card Game', '2013', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Island Siege', 'APE Games', 'Card Game', '2013', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('JAB: Realtime Boxing', 'Tasty Minstrel Games', 'Card Game', '2011', 15 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Jackson & Sheridan', 'Worthington Publishing, LLC', '', '2015', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Jenseits von Theben', 'Prinz Spiele', 'Exploration', '2004', 75 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('The Kaiser''s Pirates', 'GMT Games', 'Card Game', '2007', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Kanban: Automotive Revolution', 'Giochix.it', 'Economic', '2014', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Kemet', 'Asmodee', 'Ancient', '2012', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Killer Bunnies and the Journey to Jupiter', 'Playroom Entertainment', 'Card Game', '2008', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Killer Bunnies and the Quest for the Magic Carrot', 'Edge Entertainment', 'Animals', '2002', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Killer Bunnies: Heroes vs. Villains – Blue Starter Deck', 'Playroom Entertainment', 'Animals', '2013', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Kinder Bunnies: Their First Adventure', 'Playroom Entertainment', 'Card Game', '2005', 20 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('King of Chicago', 'TUSBAS Alliance', 'Mafia', '2005', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('King of New York', 'IELLO', 'Dice', '2014', 40 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('King''s Forge', 'Game Salute', 'Dice', '2014', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Kings of Air and Steam', 'Tasty Minstrel Games', 'Aviation / Flight', '2013', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Krosmaster: Arena', 'Abysse Corp.', 'Collectible Components', '2012', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Labyrinth: The War on Terror, 2001 – ?', 'GMT Games', 'Modern Warfare', '2010', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Lagoon: Land of Druids', 'Three Hares Games', 'Adventure', '2014', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Last Frontier: The Vesuvius Incident', 'Fat Messiah Games', 'Science Fiction', '1993', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Last Night on Earth: The Zombie Game', 'Flying Frog Productions', 'Fighting', '2007', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('The Last Spike', 'Columbia Games', 'Economic', '2015', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Leaving Earth', 'The Lumenaris Group, Inc.', 'Science Fiction', '2015', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Lee''s Invincibles', 'Worthington Publishing, LLC', 'American Civil War', '2015', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Legacy: Gears of Time', 'Floodgate Games', 'Card Game', '2012', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Legacy: The Testament of Duke de Crecy', 'Portal Games', 'Age of Reason', '2013', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Legend of the Five Rings', 'Alderac Entertainment Group', 'Card Game', '1995', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Legendary Encounters: An Alien Deck Building Game', 'Upper Deck Entertainment', 'Card Game', '2014', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Legendary: A Marvel Deck Building Game', 'Upper Deck Entertainment', 'Card Game', '2012', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Legendary: Dark City', 'Upper Deck Entertainment', 'Card Game', '2013', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Legends of Andor', 'KOSMOS', 'Adventure', '2012', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Legends of the Ancient World: The Gates to the Underworld', 'Dark City Games, Inc.', 'Adventure', '2005', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Legends of Time and Space: The Dark Star Incident', 'Dark City Games, Inc.', 'Adventure', '2008', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Legends of Time and Space: Void Station 57', 'Dark City Games, Inc.', 'Adventure', '2006', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Legion of Honor', 'Clash of Arms Games', 'Adventure', '2014', 480 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Legions of Darkness', 'Victory Point Games', 'Fantasy', '2011', 30 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Level 7 [Escape]', 'Privateer Press', 'Horror', '2012', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Lewis & Clark', 'Ludonaute', 'American West', '2013', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Liberty or Death: The American Insurrection', 'GMT Games', 'American Revolutionary War', '2016', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Liberty: The American Revolution 1775-83', 'Columbia Games', 'Age of Reason', '2003', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Lincoln''s War', 'Multi-Man Publishing', 'American Civil War', '2013', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Lock 'n Load Tactical: Day of Heroes', 'Lock 'n Load Publishing, LLC.', 'Modern Warfare', '2008', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('London', 'Mayfair Games', 'City Building', '2010', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('The Lord of the Rings: The Card Game', 'ADC Blackfire Entertainment', 'Card Game', '2011', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Lords of Waterdeep', 'Wizards of the Coast', 'City Building', '2012', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Machina Arcana', '(Self-Published)', 'Adventure', '2014', 150 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Mage Knight Board Game', 'WizKids Games', 'Adventure', '2011', 150 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Mage Knight Board Game: The Lost Legion', 'Asmodee', 'Adventure', '2012', 240 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Magic Realm', '(Self-Published)', 'Adventure', '1979', 240 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('The Manhattan Project', 'Asmodee', 'Aviation / Flight', '2012', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Mansions of Madness', 'Arclight', 'Adventure', '2011', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Master and Commander: The Far Side of the World', 'Front Porch Classics', 'Card Game', '2003', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Memoir ''44', 'Days of Wonder', 'Wargame', '2004', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Memoir ''44: Air Pack', 'Days of Wonder', 'Aviation / Flight', '2007', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Merchant of Venus (second edition)', 'Arclight', 'Economic', '2012', 240 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Merchants & Marauders', 'Asterion Press', 'Adventure', '2010', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Metro', 'Queen Games', 'Trains', '1997', 30 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Mice and Mystics', 'Plaid Hat Games', 'Adventure', '2012', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('MidEvil Deluxe', 'Twilight Creations, Inc.', 'Horror', '2009', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Might & Magic Heroes', 'Axel', 'City Building', '2012', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Mistfall', 'Games Factory Publishing', 'Adventure', '2015', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Modern Naval Battles: Global Warfare', 'DVG', 'Card Game', '2008', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Moonbase Alpha', 'Victory Point Games', 'Science Fiction', '2012', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Munchkin Quest', 'Black Monk', 'Adventure', '2008', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Mutant Chronicles: Siege of the Citadel', 'Casper', 'Science Fiction', '1993', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Mysterium', 'Asmodee', 'Deduction', '2015', 42 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Myth', 'Mercs, LLC', 'Adventure', '2014', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Mythotopia', 'Treefrog Games', 'Fantasy', '2014', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Nations', 'Lautapelit.fi', 'Card Game', '2013', 200 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Nations: The Dice Game', 'Asmodee', 'Civilization', '2014', 40 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Nauticus', 'KOSMOS', 'Economic', '2013', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Navajo Wars', 'GMT Games', 'American Indian Wars', '2013', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Neanderthal', 'Sierra Madre Games', 'Card Game', '2015', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Nemo''s War', 'Victory Point Games', 'Nautical', '2009', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('The New Science', 'Conquistador Games, Inc.', 'Educational', '2013', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('New York 1901', 'ADC Blackfire Entertainment', 'City Building', '2015', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Nexus Ops', 'Avalon Hill (Hasbro)', 'Exploration', '2005', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Nuklear Winter '68', 'Lock 'n Load Publishing, LLC.', 'Fantasy', '2012', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Omen: A Reign of War', 'Small Box Games', 'Ancient', '2011', 30 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('One Zero One', 'The Game Crafter, LLC', 'Abstract Strategy', '2013', 15 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Ora et Labora', 'Lookout Games', 'City Building', '2011', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Outpost', 'Stronghold Games', 'Economic', '1991', 150 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Panamax', 'MESAboardgames', 'Economic', '2014', 100 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Pandemic', 'Z-Man Games', 'Medical', '2008', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Pandemic Legacy: Season 1', 'Z-Man Games', 'Environmental', '2015', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Pandemic: On the Brink', 'Albi', 'Environmental', '2009', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Pandemic: The Cure', 'Asmodee', 'Dice', '2014', 30 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Panzer (second edition)', 'GMT Games', 'Wargame', '2012', 0 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Panzer General: Allied Assault', 'Petroglyph', 'Wargame', '2010', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Patchistory', 'Deinko Games', 'Bluffing', '2013', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Pathfinder Adventure Card Game: Rise of the Runelords – Base Set', 'Paizo Publishing', 'Card Game', '2013', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Paths of Glory', 'Devir', 'Wargame', '1999', 480 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Peloponnes', 'Blue Orange (EU)', 'Ancient', '2009', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Phantom Fury', 'Nuts! Publishing', 'Modern Warfare', '2011', 240 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('The Phantom League', 'Dragon Dawn Productions', 'Fighting', '2010', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Picket Duty: Kamikaze Attacks against U.S. Destroyers – Okinawa, 1945', 'Legion Wargames', 'Nautical', '2013', 0 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('The Pillars of the Earth', '999 Games', 'Economic', '2006', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Pirateer', '(Self-Published)', 'Nautical', '1978', 15 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Planet Steam', 'Edge Entertainment', 'Economic', '2008', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Police Precinct', 'Common Man Games', 'Bluffing', '2013', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Polis: Fight for the Hegemony', '(Web published)', 'Ancient', '2012', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Posthuman', 'Mighty Box', 'Adventure', '2015', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Prime Time', 'Golden Egg Games', 'Economic', '2015', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Progress: Evolution of Technology', 'NSKN Games', 'Card Game', '2014', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Quantum', 'Asterion Press', 'Civilization', '2013', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Quarantine', 'Mercury Games', 'Medical', '2013', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Quarriors!', 'WizKids Games', 'Dice', '2011', 30 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Race for the Galaxy', 'Rio Grande Games', 'Card Game', '2007', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Race for the Galaxy: Rebel vs Imperium', 'ABACUSSPIELE', 'Card Game', '2009', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Race for the Galaxy: The Brink of War', 'ABACUSSPIELE', 'Card Game', '2010', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Race for the Galaxy: The Gathering Storm', 'ABACUSSPIELE', 'Card Game', '2008', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('RAF: The Battle of Britain 1940', 'Decision Games (I)', 'Aviation / Flight', '2009', 300 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Raiders of the North Sea', 'Ediciones Primigenio', 'Medieval', '2015', 80 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Rebel Raiders on the High Seas', 'GMT Games', 'American Civil War', '2013', 360 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Red November', 'Arclight', 'Fantasy', '2008', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Renegade', 'Victory Point Games', 'Science Fiction', '2016', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Resident Evil Deck Building Game', 'Bandai', 'Card Game', '2010', 30 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Resident Evil Deck Building Game: Alliance', 'Bandai', 'Card Game', '2011', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Resident Evil Deck Building Game: Nightmare', 'Bandai', 'Card Game', '2011', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Rise of the Zombies!', 'DVG', 'Card Game', '2013', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Rivet Wars: Eastern Front', 'Asmodee', 'Miniatures', '2013', 30 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Roads & Boats', 'Splotter Spellen', 'City Building', '1999', 240 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Robinson Crusoe: Adventures on the Cursed Island', 'Portal Games', 'Adventure', '2012', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Robo Rally', '999 Games', 'Miniatures', '1994', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Robot Turtles', '(Self-Published)', 'Children''s Game', '2013', 15 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Roll for the Galaxy', 'Games Factory Publishing', 'Civilization', '2014', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Roll Through the Ages: The Bronze Age', 'Eagle-Gryphon Games', 'Ancient', '2008', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Romolo o Remo?', 'Giochix.it', 'Ancient', '2013', 150 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Rune Age', 'Arclight', 'Card Game', '2011', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Runebound (Second Edition)', '(Unknown)', 'Adventure', '2005', 240 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Runebound: The Island of Dread', 'Arclight', 'Adventure', '2005', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Runewars', 'Edge Entertainment', 'Adventure', '2010', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Secret Weapons of the Third Reich', 'The Game Crafter, LLC', 'Science Fiction', '2015', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Secrets of the Lost Tomb', 'Everything Epic Games', 'Adventure', '2015', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Sentinel Tactics: The Flame of Freedom', 'Greater Than Games (Sentinel Comics)', 'Comic Book / Strip', '2014', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Sentinels of the Multiverse', 'Gigante Jogos', 'Card Game', '2011', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Sergeants Miniatures Game: Day of Days', 'Lost Battalion Games', 'Miniatures', '2011', 0 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Sergeants Miniatures Game: La Fi�re Bridge', 'Lost Battalion Games', 'Expansion for Base-game', '2012', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Sergeants Miniatures Game: Road to Carentan', 'Lost Battalion Games', 'Expansion for Base-game', '2011', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Shadowrift', 'Game Night Productions', 'Card Game', '2012', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Shadowrun: Crossfire', 'Catalyst Game Labs', 'Adventure', '2014', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Shadows of Brimstone: City of the Ancients', 'Flying Frog Productions', 'Adventure', '2014', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Shadows of Brimstone: Swamps of Death', 'Flying Frog Productions', 'Adventure', '2014', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Sherlock Holmes Consulting Detective', 'Asmodee', 'Deduction', '1981', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Shipyard', 'Czech Games Edition', 'Economic', '2009', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Sid Meier''s Civilization: The Board Game', '(Unknown)', 'City Building', '2010', 240 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Sid Meier''s Civilization: The Boardgame', 'Eagle-Gryphon Games', 'Ancient', '2002', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Skyline', 'Tasty Minstrel Games', 'City Building', '2012', 20 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Slapshot', '(Web published)', 'Card Game', '1982', 30 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Small World', 'Days of Wonder', 'Fantasy', '2009', 80 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Small World Realms', 'Days of Wonder', 'Civilization', '2012', 80 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Small World Underground', 'Days of Wonder', 'Fantasy', '2011', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Smash Up', 'Alderac Entertainment Group', 'Card Game', '2012', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Smash Up: Awesome Level 9000', 'Alderac Entertainment Group', 'Card Game', '2013', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Smash Up: The Obligatory Cthulhu Set', 'Alderac Entertainment Group', 'Card Game', '2013', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Space Cadets: Away Missions', 'Stronghold Games', 'Adventure', '2015', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Space Empires: 4X', 'GMT Games', 'Bluffing', '2011', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Space Hulk (fourth edition)', 'Games Workshop Ltd.', 'Fighting', '2014', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Space Hulk: Death Angel – The Card Game', 'Delta Vision Publishing', 'Card Game', '2010', 30 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Space Infantry', 'Lock ''n Load Publishing, LLC.', 'Science Fiction', '2010', 20 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Spearpoint 1943', 'Collins Epic Wargames', 'Card Game', '2010', 30 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Spearpoint 1943: Village and Defensive Line Map Expansion', 'Collins Epic Wargames', 'Card Game', '2012', 30 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Spike', 'R&R Games', 'Trains', '2014', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Star Borders: Aliens', 'Victory Point Games', 'Science Fiction', '2013', 0 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Star Borders: Humanity', 'Victory Point Games', 'Science Fiction', '2010', 30 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Star Trek: Fleet Captains', 'WizKids Games', 'Miniatures', '2011', 75 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Star Wars Customizable Card Game', 'Decipher', 'Card Game', '1995', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Star Wars:  Escape From Death Star Game', 'Borras Plana S.A.', 'Adventure', '1977', 20 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Star Wars: Imperial Assault', 'Asterion Press', 'Adventure', '2014', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Star Wars: The Card Game', 'Edge Entertainment', 'Card Game', '2012', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Star Wars: X-Wing Miniatures Game', 'Fantasy Flight Games', 'Aviation / Flight', '2012', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Star Wars: Yoda the Jedi Master', 'Kenner', 'Children''s Game', '1981', 20 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('StarCraft: The Board Game', 'Edge Entertainment', 'Civilization', '2007', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('StarCraft: The Board Game – Brood War Expansion', 'Edge Entertainment', 'Civilization', '2008', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Steel Wolves: The German Submarine Campaign Against Allied Shipping – Vol 1', 'Compass Games', 'Nautical', '2010', 3000 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Stockpile', 'Nauvoo Games', 'Economic', '2015', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Stone & Relic', 'Small Box Games', 'Card Game', '2013', 30 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Storm the Castle!', 'Giant Goblin Games', 'Fantasy', '2013', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Stronghold', 'Portal Games', 'Fantasy', '2009', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Struggle for the Galactic Empire', 'Decision Games (I)', 'Science Fiction', '2009', 240 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Struggle of Empires', 'Arclight', 'Civilization', '2004', 240 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Student Bodies', 'Angry Duck Games LLC', 'Horror', '2014', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('A Study in Emerald (second edition)', 'Treefrog Games', 'Horror', '2015', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Suburbia', 'B�zier Games, Inc.', 'City Building', '2012', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Summoner Wars', 'Plaid Hat Games', 'Card Game', '2009', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Summoner Wars: Master Set', 'Plaid Hat Games', 'Card Game', '2011', 30 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Super Munchkin', 'Edge Entertainment', 'Card Game', '2005', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Survive: Escape from Atlantis!', 'Parker Brothers', 'Adventure', '1982', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Swing States 2012', 'Victory Point Games', 'Educational', '2012', 40 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('T.I.M.E Stories', 'Space Cowboys', 'Adventure', '2015', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Tales of the Arabian Nights', 'Devir', 'Adventure', '2009', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Talisman (Revised 4th Edition)', 'Black Industries', 'Adventure', '2007', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Tannh�user', 'Edge Entertainment', 'Fantasy', '2007', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Terra Mystica', 'Feuerland Spiele', 'Civilization', '2012', 150 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Terror in Meeple City', 'Repos Production', 'Action / Dexterity', '2013', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Through the Ages: A Story of Civilization', 'Czech Board Games', 'Civilization', '2006', 240 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Thunder Alley', 'GMT Games', 'Racing', '2014', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Thunderbolt Apache Leader', 'DVG', 'Aviation / Flight', '2012', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Thunderstone', 'Alderac Entertainment Group', 'Card Game', '2009', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Thunderstone Advance: Caverns of Bane', 'Alderac Entertainment Group', 'Card Game', '2012', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Thunderstone Advance: Root of Corruption', 'Alderac Entertainment Group', 'Card Game', '2012', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Thunderstone Advance: Towers of Ruin', 'Alderac Entertainment Group', 'Card Game', '2012', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Thunderstone: Dragonspire', 'Alderac Entertainment Group', 'Card Game', '2011', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Thunderstone: Wrath of the Elements', 'Alderac Entertainment Group', 'Card Game', '2010', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Ticket to Ride', 'Days of Wonder', 'Trains', '2004', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Ticket to Ride: M�rklin', 'Days of Wonder', 'Trains', '2006', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Tide of Iron', 'Edge Entertainment', 'Wargame', '2007', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Tide of Iron: Normandy', 'Fantasy Flight Games', 'Expansion for Base-game', '2008', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Tiger Leader', 'DVG', 'Wargame', '2015', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Tiny Epic Defenders', '(Web published)', 'Fantasy', '2015', 30 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Tiny Epic Kingdoms', 'Gamelyn Games', 'Bluffing', '2014', 30 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Tobruk:  Tank Battles in North Africa 1942', 'Avalon Hill', 'Wargame', '1975', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Tomorrow the World', '3W (World Wide Wargames)', 'Science Fiction', '1989', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('A Touch of Evil: Something Wicked Expansion', 'Flying Frog Productions', 'Adventure', '2009', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('A Touch of Evil: The Supernatural Game', 'Flying Frog Productions', 'Adventure', '2008', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Trains', 'Alderac Entertainment Group', 'Card Game', '2012', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Trickerion: Legends of Illusion', 'APE Games', 'Fantasy', '2015', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Triumph & Tragedy', 'GMT Games', 'Economic', '2015', 240 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Twilight Imperium (Third Edition)', 'Fantasy Flight Games', 'Civilization', '2005', 240 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Twilight Struggle', 'GMT Games', 'Modern Warfare', '2005', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Tzolk''in: The Mayan Calendar', 'Czech Games Edition', 'Ancient', '2012', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('U-Boat Leader', 'DVG', 'Nautical', '2011', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Upon a Fable', 'Dyskami Publishing Company', 'Abstract Strategy', '2013', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Urban Operations', 'Nuts! Publishing', 'Bluffing', '0', 300 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Urban Sprawl', 'GMT Games', 'City Building', '2011', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Urbania', 'Mayfair Games', 'City Building', '2012', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('UWO', 'Elven Ear Games', 'Card Game', '2004', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('The Valkyrie Incident', 'Small Box Games', 'Card Game', '2013', 30 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Ventura', 'Fantasy Flight Games', 'Fighting', '2011', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Virgin Queen', 'GMT Games', 'Negotiation', '2012', 420 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('War of the Ring (second edition)', 'Ares Games', 'Adventure', '2012', 150 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('War! Age of Imperialism', 'Eagle-Gryphon Games', 'Industry / Manufacturing', '2001', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Warhammer 40,000: Conquest', 'Edge Entertainment', 'Card Game', '2014', 45 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Warmachine: High Command', 'Privateer Press', 'Card Game', '2013', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Warparty', 'Lock ''n Load Publishing, LLC.', 'Adventure', '2013', 150 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Warriors & Traders', 'NSKN Games', 'Economic', '2011', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Washington''s War', 'GMT Games', 'Age of Reason', '2010', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('We Were Brothers', 'WBS Games', 'Collectible Components', '2015', 300 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Western Town', '(Web published)', 'American West', '2005', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Where There Is Discord: War in the South Atlantic', 'Fifth Column Games', 'Modern Warfare', '2009', 240 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Wing Leader: Victories 1940-1942', 'GMT Games', 'Aviation / Flight', '2015', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Wizard Kings', 'Columbia Games', 'Fantasy', '2000', 150 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Wizard Kings: Expansion Armies', 'Columbia Games', 'Collectible Components', '2000', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('A World at War', 'GMT Games', 'Wargame', '2003', 2880 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('World at War: America Conquered', 'Lock ''n Load Publishing, LLC.', 'Wargame', '2013', 240 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('World at War: Blood and Bridges', 'Lock ''n Load Publishing, LLC.', 'Modern Warfare', '2008', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('World at War: Eisenbach Gap', 'Lock ''n Load Publishing, LLC.', 'Modern Warfare', '2007', 90 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('World in Flames', 'Australian Design Group', 'Wargame', '1985', 6000 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('World War II: Barbarossa to Berlin', 'GMT Games', 'Wargame', '2002', 420 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('XenoShyft: Onslaught', 'Cool Mini Or Not', 'Card Game', '2015', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Zombicide', 'Asmodee', 'Horror', '2012', 60 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Zombicide Season 2: Prison Outbreak', 'Asmodee', 'Horror', '2013', 120 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Zombie State: Diplomacy of the Dead', 'Zombie State Games', 'Industry / Manufacturing', '2010', 180 );
INSERT INTO games ( title, publisher, genre, released, playtime) VALUES('Zpocalypse', 'Greenbrier Games', 'Exploration', '2013', 100 );
